export const Publicholidays=[
    {}
]
export const monthsNames=[
    {
      monthName:"Jan",
      incrementNum:-6
    },
    {
      monthName:"Feb",
      incrementNum:-5
    },
    {
      monthName:"Mar",
      incrementNum:-4,
    },
    {
      monthName:"Apr",
      incrementNum:-3,
    },
    {
      monthName:"May",
      incrementNum:-2,
    },
    {
      monthName:"Jun",
      incrementNum:-1,
    },
    {
      monthName:"Jul",
      incrementNum:0,
    },
    {
      monthName:"Aug",
      incrementNum:1,
    },
    {
      monthName:"Sep",
      incrementNum:2,
    },
    {
      monthName:"Oct",
      incrementNum:3,
    },
    {
      monthName:"Nov",
      incrementNum:4,
    },
    {
      monthName:"Dec",
      incrementNum:5,
    },
  ]